-- phpMyAdmin SQL Dump
-- version 4.8.3
-- https://www.phpmyadmin.net/
--
-- Hôte : localhost:3306
-- Généré le :  Dim 08 déc. 2019 à 22:23
-- Version du serveur :  5.7.24
-- Version de PHP :  7.3.7

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données :  `vosges`
--

-- --------------------------------------------------------

--
-- Structure de la table `objets`
--

CREATE TABLE `objets` (
  `id` int(11) NOT NULL,
  `latitude` double NOT NULL,
  `longitude` double NOT NULL,
  `texte` text NOT NULL,
  `image` text NOT NULL,
  `statut` int(11) NOT NULL,
  `fils` text NOT NULL,
  `zoom` int(11) NOT NULL,
  `trouve` int(11) NOT NULL,
  `type` text NOT NULL,
  `fils_verrou` text NOT NULL,
  `inventaire` int(11) NOT NULL,
  `intermediaire` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `objets`
--

INSERT INTO `objets` (`id`, `latitude`, `longitude`, `texte`, `image`, `statut`, `fils`, `zoom`, `trouve`, `type`, `fils_verrou`, `inventaire`, `intermediaire`) VALUES
(1, 48.039899, 7.136699, '<p>Bienvenue à Munster votre point de départ. Tout d\\\'abord nous vous invitons de chercher le fromage local dans les rues de Munster. Ensuite, vous pourrez vous diriger vers le col de la Schlucht à l\\\'Ouest en passant par Stosswihr. Attention de nombreux secrets ont été disséminés partout plus vous en trouverez, plus votre score final sera élevé !  </p><button type=\"button\" name=\"button\" id=\"bouton\">Continuer</button>\r\n', 'drapeau_depart', 1, '2;1000;1001;1002;1010,1030', 13, 0, 'etape', '', 0, 0),
(2, 48.064072, 7.023382, '<p>Félicitations, vous avez gravi ce premier col vosgien. Il est situé à 1139m d\'altitude pour une montée de 14 km à 4,2% (soit 759m de dénivelés). Dans ce sens, il a été gravi pour la dernière fois en 2005. <br><br> Ce n\'est pas tout ça mais monter un col fait transpirer. Vous allez donc descendre la route vers l\'Ouest pour faire une halte au lac de Longemer</p><button type=\"button\" name=\"button\" id=\"bouton\">Continuer</button>', 'redflag', 0, '1003;1011;3;1025', 14, 0, 'etape', '', 0, 0),
(3, 48.068166, 6.950131, '<p>Vous voilà rafraîchis, et près à repartir sur les chapeaux de roue. Il est temps de vous diriger vers la ville où jadis vécut Gérard. <br><br>N\'oubliez pas que vous pouvez trouver des trésors, n\'hésitez pas à zoomer ou à sortir des sentiers battus, certains sont bien cachés.</p><button type=\"button\" name=\"button\" id=\"bouton\">Continuer</button> ', 'greenflag', 0, '4;1004', 14, 0, 'etape', '', 0, 0),
(4, 48.070441, 6.874736, '<p>Le vélo est une activité qui donne soif. Le problème est que vous êtes novices et que vous avez oublié de remplir votre gourde d\'eau au départ. Vous allez donc vous mettre en quête d\'une fontaine à eau potable (parce que vous ne faites pas parties des personnes qui osent boire n\'importe quelle eau). Le but de ce premier mini-jeu est de trouver la bonne fontaine.</p><button type=\"button\" name=\"button\" id=\"bouton\">Découvrir le mini-jeu!</button>', 'blueflag', 0, '5;6;7;1026', 14, 0, 'fontaine', '8', 0, 0),
(5, 48.079613, 6.863943, '<center>Fontaine des airelles :\r\n\r\nhdx qrq frqwuroh<center>\r\n', 'fontaine', 0, '', 14, 0, 'affichage', '', 0, 1),
(6, 48.077108, 6.881796, '<center>Fontaine des lilas :\r\n\r\nhdx srwdeoh<center>', 'fontaine', 0, '', 14, 0, 'affichage', '', 0, 1),
(7, 48.064221, 6.872226, '<center>Fontaine des sapins :\r\n\r\nhdx gh vrxufh<center>', 'fontaine', 0, '', 14, 0, 'affichage', '', 0, 1),
(8, 48.026367, 6.885562, '<p>Et de deux, gardez le rythme vous allez devoir en affronter encore une belle quantité ! Le col de Grosse Pierre perché à 955 m d\'altitude nécessite 8,4 km de montée à 3,4%. La pente est trompeuse car le col se fait en deux temps (avec une partie de redescente. Dans ce sens, il a été gravi pour la dernière fois en 2012. <br></br>Par contre, vous n\'avez pas su gérer vos vitesses correctement... si bien que vous avez cassé votre patte de dérailleur (la pièce qui maintient le dérailleur au cadre du vélo). Dirigez-vous vers l\'église de La Bresse en bas du col pour voir la suite des instructions</p><button type=\"button\" name=\"button\" id=\"bouton\">Continuer</button>', 'redflag', 0, '9;1005', 14, 0, 'etape', '', 0, 0),
(9, 48.005165, 6.875034, '<p>Vous voici arrivés au niveau de l\'église de La Bresse où vous réaliserez les réparations une fois que vous aurez réunis le matériel nécessaire. Il vous faudra donc obtenir des outils dans la quincaillerie, ainsi qu\'une nouvelle patte de dérailleur chez le vendeur de vélos. Votre objectif est de remplir votre inventaire avec ses deux objets.</p><button type=\"button\" name=\"button\" id=\"bouton\">Découvrir le mini-jeu!</button>', 'blueflag', 0, '10;11;1006;1029;1017;1007', 14, 0, 'reparer_patte', '13', 0, 0),
(10, 48.007212, 6.881403, '<p>Vous voici à la quincaillerie locale (dont on ne citera pas le nom pour ne pas faire de placement de produit). Vous n\'avez plus qu\'à cliquer sur le bouton ci-dessous pour mettre les outils dans votre inventaire.</p><button type=\"button\" name=\"button\" id=\"bouton\">Placer dans l\'inventaire</button>', 'outils', 0, '', 14, 0, 'simple_collecte', '', 0, 1),
(11, 48.007551, 6.88293, '<p>Vous voici au magasin de vélo. Vous allez voir le vendeur et ce dernier vous demande la référence de votre patte de dérailleur. Le problème, c\'est que vous ne la connaissez pas. Vous devez donc aller à la bibliothèque pour aller chercher un papier sur lequel est écrit toutes les informations relatives à votre vélo ! (Comme ça vous êtes sûrs que le vendeur ne vous donne pas n\'importe quoi)</p><button type=\"button\" name=\"button\" id=\"bouton\">Aller voir la bibliothèque</button>', 'patte de dérailleur', 0, '12', 14, 0, 'patte', '', 0, 1),
(12, 47.99979, 6.867199, '<p>Après quelques minutes de recherche difficiles, voici enfin votre papier, vous n\'avez plus qu\'à l\'imprimer et à le collecter</p><button type=\"button\" name=\"button\" id=\"bouton\">Imprimer puis collecter</button>', 'caractéristiques vélo', 0, '', 14, 0, 'simple_collecte', '', 0, 1),
(13, 48.000255, 6.945586, '<p>Le col de Bramont à 956 m d\'altitude est un col des Vosges très spécial, puisque la route  décrit 14 épingles. La descente vers l\'Alsace est donc très agréable. Du côté lorrain, la montée dure 7,9 km depuis La Bresse pour un dénivelé de 320 m. En réalité, seul les trois derniers kilomètres sont plus difficiles.\r\n<br></br>Vous allez donc descendre cette route divertisante, jusqu\'au lac de Kruth-Wildenstein.</p><button type=\"button\" name=\"button\" id=\"bouton\">Continuer</button>', 'redflag', 0, '14;1008;1012;1009', 14, 0, 'etape', '', 0, 0),
(14, 47.955684, 6.961802, '<p>Fini la rigolade, il faut à nouveau monter un col difficile : le Markstein. Le Markstein est situé à 1183 m d\'altitude et est l\'un des cols les plus hauts des Vosges. La montée dure 14 km depuis l\'endroit où vous êtes et correspond à 602 m de dénivelé. Le tour de France n\'a jamais monté le Markstein par ce côté mais a bien tort ! Petite remarque, les vrais bressauds sauteront au plafond quand ils remarqueront que nous ne sommes pas passés par la route des américains directement pour aller au Markstein. <br></br> Il vous reste donc à gravir cette côte !.</p><button>Continuer</button>', 'greenflag', 0, '15', 14, 0, 'etape', '', 0, 0),
(15, 47.922924, 7.032603, '<p>Vous voilà enfin au sommet de cette montée (on ne va pas la représenter). Même si c\'est pas aussi long que la montagne de Lure, cela reste un bon défi. <br></br> Passons au choses sérieuses, cela fait longtemps que nous n\'avons pas fait de jeu. Voici l\'objectif du prochain : Vous allez descendre la D430 jusqu\'à Guebwiller où vous pourrez constituer un puzzle pour connaître la suite du parcours. Cependant, ils vous faudra récupérer des pièces à 4 endroits, et cela va se mériter car il faudra zoomer beaucoup pour les trouver.</p><button type=\"button\" name=\"button\">Commencer le mini-jeu !</button>\r\n', 'redflag', 0, '16;17;18;19;20;1013;1023', 14, 0, 'etape', '', 0, 0),
(16, 47.93614, 7.045636, '<p>Nous avons omis un petit détail, il faudra répondre à des petites questions sur le vélo pour continuer. <br></br> Mon vélo dispose de trois plateaux, quel est le plateau le plus adapté pour les montées raides ? (Ecrivez le nombre correspondant puis validez)</p><input type=\"text\" name=\"plateau\"><button type=\"button\" name=\"button\">Validez votre réponse</button>', 'piece', 0, '', 15, 0, 'piece1', '', 0, 1),
(17, 47.935713, 7.091086, '<p>Nous avons omis un petit détail, il faudra répondre à des petites questions sur le vélo pour continuer. <br></br>Quelle est la meilleure combinaison de plateaux/vitesses qu\'il faut privilégier sachant que le vélo dispose de 3 plateaux et 7 vitesses (Cochez la meilleure réponse) ? </p><label>plateau 3 / vitesse 1<input type=\"radio\" name=\"ouinon\" value=\"3/1\"></label>\r\n<label>plateau 3 / vitesse 4<input type=\"radio\" name=\"ouinon\" value=\"3/4\"></label><label>plateau 2 / vitesse 4 <input type=\"radio\" name=\"ouinon\" value=\"2/4\"></label><label>plateau 1 / vitesse 6<input type=\"radio\" name=\"ouinon\" value=\"1/6\"></label><label>plateau 1 / vitesse 4<input type=\"radio\" name=\"ouinon\" value=\"1/4\"></label><label>plateau 2 / vitesse 2<input type=\"radio\" name=\"ouinon\" value=\"2/2\"></label><button type=\\\"button\\\" name=\\\"button\\\">Validez votre réponse</button>', 'piece', 0, '', 15, 0, 'piece2', '', 0, 1),
(18, 47.945145, 7.12799, '<p>Continuons les questions. <br></br> Le port du casque de vélo est-il obligatoire (dans tous les cas seuls les grands cyclistes portent le casque) ?</p><label>Oui<input type=\"radio\" name=\"ouinon\" value=\"1\"></label>\r\n<label>Non<input type=\"radio\" name=\"ouinon\" value=\"0\"></label><button type=\"button\" name=\"button\">Validez-votre réponse</button>', 'piece', 0, '', 15, 0, 'piece3', '', 0, 1),
(19, 47.939529, 7.160637, '<p>Voici la dernière question (après tout dépend d\'où vous avez commencé). <br></br> Quel matériau composant les cadres des vélos est le moins dense ?</p><label>Aluminium<input type=\"radio\" name=\"ouinon\" value=\"alu\"></label>\r\n<label>Acier<input type=\"radio\" name=\"ouinon\" value=\"acier\"></label></label>\r\n<label>Carbone<input type=\"radio\" name=\"ouinon\" value=\"carbone\"></label><button id = \'jouer\' type=\"button\" name=\"button\">Validez votre réponse</button>', 'piece', 0, '', 15, 0, 'piece4', '', 0, 1),
(20, 47.909564, 7.21395, '<p>Voici la zone où vous devrez reconstituer le puzzle</p><button id = \'jouer\' type=\"button\" name=\"button\">Reconstituer le puzzle !</button>', 'blueflag', 0, '', 14, 0, 'puzzle', '21;1014;1015', 0, 1),
(21, 47.860938, 7.213636, '<p>Vous voici donc à Hartsmannwiller, charmant village au pied des vignes. Vouas allez poursuivre votre périple en poursuivant la D5 jusqu\'à Cernay.</p><button id = \"valider\">Continuer</button>', 'greenflag', 0, '22;1019;1028;1016', 14, 0, 'etape', '', 0, 0),
(22, 47.810388, 7.178424, '<p>Vous voici à Cernay quasiment à l\'extrémité de la route des vins. Rendez-vous à présent à Thann à l\'Est qui constitue l\'extrémité Sud de la route des vins.</p><button id = \"valider\">Continuer</button>', 'greenflag', 0, '23', 14, 0, 'etape', '', 0, 0),
(23, 47.803269, 7.111583, '<p>Les pépins sont de retour. Vous remarquez que votre roue est crevée et pour cause votre pneu usé est troué (basé sur l\'histoire vraie d\'un cycliste pas assez prévoyant). Vous allez donc devoir acheté l\'équipement nécessaire (chambre à air plus pneu) chez le marchand de vélo local en plus d\'une pompe. C\'est l\'heure d\'un nouveau mini-jeu.</p><button id = \"valider\">Découvrir le mini-jeu !</button>', 'blueflag', 0, '24', 14, 0, 'reparation_pneu', '27', 0, 0),
(24, 47.79803, 7.114748, '<p>Vous voici chez le marchand de vélo, vous n\'avez plus qu\'à obtenir votre bonheur !</p><button id = \"valider\">Obtenir l\'équipement</button>', 'équipement', 0, '25', 14, 0, 'marchand_pneu', '26', 0, 1),
(25, 47.8051, 7.095222, '<p>C\'est votre jour de chance, vous trouvez une personne qui vous propose de vous donner un billet en échange d\'un petit service</p><button id = \"valider\">Découvrir la proposition</button>', 'billet', 0, '', 14, 0, 'argent', '', 0, 1),
(26, 47.797223, 7.104427, '<p>Vous voilà chez le père de l\'honnête marchand de vélo, il vous offre comme prévu une pompe de vélo après avoir entendu votre explication</p><button id = \"valider\">Obtenir la pompe</button>', 'pompe', 0, '', 14, 0, 'simple_collecte', '', 0, 1),
(27, 47.790224, 7.073399, '<p>Aïe ! Il semblerait que vous soyez tombé sur une route barrée, la seule solution envisageable consiste à retourner à Thann, puis à remonter la Thur vers le Nord-Est jusqu\'à Bitschwiller-lès-Thann.</p><button id = \"valider\">Continuer</button>', 'greenflag', 0, '28', 14, 0, 'etape', '', 0, 0),
(28, 47.829198, 7.079386, '<p>Il est temps de refaire un col après quelques dizaines de kilomètres de \"plat\". Vous allez donc prendre la route Joffre qui va vers le col du Hundsruck poyr réchauffer vos jambes.</p><button id = \"valider\">Continuer</button>', 'greenflag', 0, '29', 14, 0, 'etape', '', 0, 0),
(29, 47.806375, 7.042661, '<p>Le col du Hundsruck n\'est certainement pas la montée la plus dure des Vosges. Il s\'agit cependant d\'un col important si l\'on souhaite enchaîner les montées du Grand Ballon et du Ballon d\'Alsace (au passage, il s\'agit bien de deux sommets différents, le Grand Ballon d\'Alsace n\'existe pas). Ce col est perché à 748 m d\'altitude pour un dénivelé de 374 m et une pente de 6,9% sur 5,5km. <br></br>Continuez sur la route Joffre jusqu\'à Masevaux (en passant par Bourbach-le-Haut puis Houppach.</p><button id = \"valider\">Continuer</button>', 'redflag', 0, '30;1020', 14, 0, 'etape', '', 0, 0),
(30, 47.775467, 6.995164, '<p>Nous voici à Masevaux, comme certaines villes d\'Alsace à l\'image de Munster, cette ville possède des secteurs pavés, ce qui est intéressant d\'un point de vue cycliste. Nous sommes proches du Territoire de Belfort et de la Haute Saône, deux départements au patrimoine très intéressant. <br></br> Remontez à présent la vallée de la Doller pour rejoindre Sewen en passant par Kirchberg entre autres.</p><button id = \"valider\">Continuer</button>', 'greenflag', 0, '31;1022;1027', 14, 0, 'etape', '', 0, 0),
(31, 47.807715, 6.905053, '<p>Vous voici à Sewen, au pied d\'une montagne mythique à plusieurs points de vue. Premièrement, il s\'agit du premier col monté par le tour de France, c\'était en 1905 mais par le versant de Giromagny (Territoire de Belfort). Deuxièmement, c\'est la seule montagne a être présente à la fois dans les trois anciennes régions de Lorraine, de Franche-Comté et d\'Alsace (le sommet était le tripoint des trois ex-régions). Le Ballon dispose de trois montées qui sont plus intéressantes les unes que les autres. La montée par Giromagny est jugée comme la plus facile car longue et peu raide. La montée par Saint-Maurice-sur-Moselle (département des Vosges) est la deuxième plus dure. Enfin le versant que vous allez attaqué par l\'Alsace est considéré comme le plus dur. <br></br> Il ne vous reste plus qu\'à le monter !</p><button id = \"valider\">Continuer</button>', 'greenflag', 0, '32;1018;1021', 14, 0, 'etape', '', 0, 0),
(32, 47.820482, 6.83465, '<p> Vous l\'avez monté ! Le col du Ballon d\'Alsace se trouve à 1170 m d\'altitude, pour un dénivelé de 670 m, une montée de 11,2 km et une pente de 6% (mais avec des passages raides surtout au niveau du lac d\'Alfeld<br></br> Éreinté, vous décidez de piquer un petit roupillon sur cette botte de paille qui a l\'air bien confortable...</p><button id = \"valider\">Continuer</button>', 'redflag', 0, '33', 14, 0, 'ballon', '', 0, 0),
(33, 47.962571, 6.455548, '<p> Vous vous réveillez, secoué par de nombreux cahots. Deux trois regards et vous comprenez vite que vous n\'êtes plus du tout au Ballon d\'Alsace ! La botte sur laquelle vous roupilliez était chargée sur une remorque et le paysan n\'a pas attendu votre réveil pour repartir ! Un peu étourdi par ce changement subit, vous arrivez à la ville la plus proche : Plombières-les-Bains. Il semblerait que vous vous soyiez un peu éloigné des montagnes pour vous diriger vers la Haute-Saône. Ce département est réputé pour sa gastronomie et son architecture, à vous de voir ce qu\'il en est réellement.\r\nVous allez donc pouvoir continuer doucement vers le Sud. </p>\r\n<button type=\"button\" name=\"button\" id=\"bouton\"> Continuer </button>', 'greenflag', 0, '34;1500', 14, 0, 'etape', '', 0, 0),
(34, 47.883971, 6.401961, '<p> Vous venez de faire vos premiers pas en Haute-Saône ! Cet endroit fourmille aussi de secrets à découvrir, cherchez bien, tout en continuant petit à petit vers le sud ! </p>\r\n<button type=\"button\" name=\"button\" id=\"bouton\">Continuer</button>', 'greenflag', 0, '35;1501;1502;1506', 14, 0, 'etape', '', 0, 0),
(35, 47.820822, 6.37725, '<p> Vous arrivez au pays de Luxeuil, une ville romaine qui était un carrefour très important dans l\'Antiquité !\r\nFouillez bien dans les alentours (parfois loin !) pour dénicher un maximum de souvenirs de cet endroit à la frontière entre les Vosges Saônoises et les plaines vers l\'Ouest et le Sud.\r\nAfin de ne pas trop vous éloigner, retourner tout de même vers l\'est, un bon chemin vous attends ! </p>\r\n<button type=\"button\" name=\"button\" id=\"bouton\">Continuer</button>', 'blueflag', 0, '36;1503;1504;1505;1507;1510;1512;1518', 14, 0, 'luxeuil', '', 0, 1),
(36, 47.852434, 6.614904, '<p> Vous venez de gravir la courte mais rude côte d\'Esmoulières, classée troisième catégorie au tour de France. Vos mollets souffrent, vos cuisses tétanisent, mais cela valait le coup : vous êtes environné par une multitude de petits étangs, bordés de murettes en pierre depuis des décennies. Ce petit coin, niché au milieu des basses Vosges, est absolument enchantant. C\'est pas le tout, on vous indique une bonne adresse à la prochaine à droite, dans quelques kilomètres ! </p>\r\n<button type=\"button\" name=\"button\" id=\"bouton\">Continuer</button>', 'redflag', 0, '37;1513;1024', 14, 0, 'etape', '', 0, 0),
(37, 47.869564, 6.666859, '<p> Décidément ça grimpe dans ce pays, même quand on est persuadé que ça devrait descendre... Enfin, vous avez atteint la bifurcation, cette fois, une descente d\'après les lignes de niveau ! Enfin, si vous savez lire une carte... </p>\r\n<button type=\"button\" name=\"button\" id=\"bouton\">Continuer</button>', 'redflag', 0, '38', 14, 0, 'etape', '', 0, 0),
(38, 47.860613, 6.677779, '<p> Cet endroit est une sorte de manifestation physique de l\'adjectif \"paumé\". 7 bâtiments, dont une auberge bien connue ce la région pour sa tenancière austère et son unique plat, omelette saucisse, et ce depuis plus de trente ans ! Un passage dans les Vosges n\'en serait pas un sans une excursion à Beulotte-Saint-Laurent, l\'incarnation du calme et de l\'éloignement de tout. La petite auberge dont on vous parlait est justement ouverte, mais le règlement ici semble un peu original... </p>\r\n<button type=\"button\" name=\"button\" id=\"bouton\">Continuer</button>', 'blueflag', 0, '39', 14, 0, 'beulotte', '', 0, 1),
(39, 47.818029, 6.684987, '<p> Incroyable ! Pas une côte depuis des kilomètres, on croit rêver... Vous êtes à Servance, petite bourgade cernée par les montagnes, pas moyen de s\'échapper. Les choses sérieuses s\'approchent, méfiance. Prenez votre courage à deux mains et filez suivre la D133. </p>\r\n<button type=\"button\" name=\"button\" id=\"bouton\">Continuer</button>', 'greenflag', 0, '40;1511', 14, 0, 'etape', '', 0, 0),
(40, 47.808942, 6.734487, '<p> Quelques kilomètres à 3-4% de moyenne viennent de s\'écouler. Vous voici à Miellin et l\'issue est inéluctable : il va falloir passer par le redoutable col des chevrères pour continuer... </p>\r\n<button type=\"button\" name=\"button\" id=\"bouton\">Continuer</button>', 'greenflag', 0, '41;1500', 14, 0, 'etape', '', 0, 0),
(41, 47.791245, 6.742345, '<p> ENFIN ! Vous n\'en voyiez pas le bout de cette côte à la pente ahurissante qui avoisine les 18% sur quelques centaines de mètres, de quoi donner le tourni quand on regarde en arrière... Vous êtes au sommet du col des Chevrères, le passage obligé avant la Planche des Belles FIlles, l\'ascension finale. Allongez-vous dans l\'herbe pour souffler, avant d\'entamer votre ultime moment de récupération : la descente vers Belfahy. On vous laisse trouver la route de la Planche seul, rassurez-vous elle est toute proche, ce qui n\'est d\'ailleurs pas si rassurant que cela...</p>\r\n<button type=\"button\" name=\"button\" id=\"bouton\">Continuer</button>', 'redflag', 0, '42;1514;1516', 14, 0, 'etape', '', 0, 0),
(42, 47.771042, 6.777255, '<p> Cette fois c\'est fini ! Plus jamais vous ne remonterez sur un vélo après tant de souffrances ! Le dernier mur de 20% vous reste en travers des quadriceps. Mais vous l\'avez fait. Du haut de la Planche, vous contemplez tous ces paysages que vous avez traversés, parfois euphorique, parfois dépité, mais toujours motivé.\r\nCette fois l\'aventure touche à sa fin. Filez prendre une bonne bière au restaurant de la Planche, et reposez-vous pendant un bon mois. Ce sera l\'occasion de repenser aux merveilles qui ont pavé votre route. Ce fut un plaisir de vous accompagner tout au long du parcours. La bise et merci d\'avoir joué ! </p>\r\n<button type=\"button\" name=\"button\" id=\"bouton\"> Siroter une bière </button>', 'planche2', 0, '', 14, 0, 'fin', '', 0, 0),
(1000, 48.083131, 7.140027, '<p>Vous voici au Linge, un lieu de mémoire de la Première Guerre.Voici un képi de soldat typique de cette époque</p><button type=\"button\" name=\"button\" id=\"bouton\">Collecter</button>', 'kepi', 0, '', 15, 0, 'secret', '', 0, 0),
(1001, 48.020649, 7.079434, '<p> C\'est ici qu\'est captée la fameuse eau Cristaline de Metzeral. Assoiffé, vous décider de vous emparer d\'une bouteille en guise de souvenir. </p>\r\n<button type=\"button\" name=\"button\" id=\"bouton\">Collecter</button>', 'cristaline', 0, '', 15, 0, 'secret', '', 0, 0),
(1002, 48.051385, 7.209513, '<p>Que serait l\'Alsace sans sa coiffe noire traditionnelle. Ce couvre-chef sympathique n\'était en réalité porté à l\'époque que dans la zone de Strasbourg</p>\r\n<button type=\"button\" name=\"button\" id=\"bouton\">Collecter</button>', 'coiffe', 0, '', 15, 0, 'secret', '', 0, 0),
(1003, 48.038389, 7.01498, '<p>Du haut de ses 1363 m, le Hohneck est le troisième plus haut sommet des Vosges. De nombreux promeneurs y passent régulièrement, et laissent parfois leurs bâtons. (Il semblerait d\'ailleurs que certains utilisent leurs batons de skis comme bâtons de randonnée)</p>\r\n<button type=\"button\" name=\"button\" id=\"bouton\">Collecter</button>\r\n', 'baton', 0, '', 15, 0, 'secret', '', 0, 0),
(1004, 48.08242, 6.92651, '<p>Voici l\'une des spécialités des Vosges côté lorrain : le pâté lorrain. Ce plat contenant de l\'échine de porc entourée de pâte feuilletée saura réveiller vos saveurs d\'antan</p>\r\n<button type=\"button\" name=\"button\" id=\"bouton\">Collecter</button>', 'pate', 0, '', 15, 0, 'secret', '', 0, 0),
(1005, 48.020743, 6.877299, '<p>Voici une roche bien particulière, bonheur des escaladeurs:son nom est Moutier des Fées. Peut-être que vous rencontrerez des êtres surnaturels si vous osez vous y aventurer nuit...</p><button type=\"button\" name=\"button\" id=\"bouton\">Collecter</button>', 'moutier', 0, '', 15, 0, 'secret', '', 0, 0),
(1006, 47.998092, 6.860951, '<p>Voici une boutique de bonbons bien connue des locaux. Vous pourrez y découvrir en particulier les fameux bonbons aux sapins qui font la fierté de la région.</p><button type=\"button\" name=\"button\" id=\"bouton\">Collecter</button>', 'bonbon', 0, '', 15, 0, 'secret', '', 0, 0),
(1007, 47.986342, 6.903459, '<p>Le lac des corbeaux est célèbre pour son reflet noir caractéristique des sapins environnants. Cette photo a été prise sur la roche du lac qui surplombe ce lac atypique.</p><button type=\"button\" name=\"button\" id=\"bouton\">Collecter</button>', 'corbeaux', 0, '', 15, 0, 'secret', '', 0, 0),
(1008, 47.992111, 6.944123, '<p>Vous voici à la Vieille Montagne (ou Altenberg pour les alsaciens). C\'est dans ce lieu que vous pourrez cueillir des brimbelles en grande quantité(vrai appellation des myrtilles). Mais attention aux quotas, vous pourriez être verbalisés par gourmandise.</p>\r\n<button type=\"button\" name=\"button\" id=\"bouton\">Collecter</button>', 'brimbelles', 0, '', 15, 0, 'secret', '', 0, 0),
(1009, 48.000651, 6.981051, '<p>Le Rothenbachkopf est un sommet très sauvage des Vosges. C\'est l\'un des seuls à disposer d\'un monticule à son sommet comme dans les Alpes. Il se dit que certaines personnes souhaiteraient voir leurs cendres répandues en ce lieu, comme une union définitive entre l\'Homme et la nature</p>\r\n<button type=\"button\" name=\"button\" id=\"bouton\">Prendre la photo</button>', 'rothenbachkopf', 0, '', 15, 0, 'secret', '', 0, 0),
(1010, 48.040612, 7.132389, '<p>Félicitations, vous avez trouvé votre premier trésor... et pas n\'importe lequel ! Il s\'agit là d\'un munster fromage odorant qui fait la fierté de la ville éponyme et du massif vosgien tout entier. Pour voir la page des trésors déjà trouvés cliquez sur \'Voir les secrets\'.<p><button type=\"button\" name=\"button\" id=\"bouton\">Collecter</button>', 'munster', 0, '', 15, 0, 'secret', '', 0, 0),
(1011, 48.053475, 6.959861, '<p>Voici une roche granitique imposante au cœur de la forêt. Son emplacement au sommet de la montagne, était peut-être perçu comme un événement surnaturel. C\'est sans doute pour cela qu\'on l\'appelle boule du diable</p><button type=\"button\" name=\"button\" id=\"bouton\">Prendre la photo</button> ', 'diable', 0, '', 15, 0, 'secret', '', 0, 0),
(1012, 47.956536, 6.895561, '<p>Situé dans le coeur de la forêt vosgienne, le grand tétras est l\'espèce emblématique des Vosges. Cette espèce est protégée et reste loin de l\'activité humaine</p><button type=\"button\" name=\"button\" id=\"bouton\">Prendre la photo</button> ', 'tetras', 0, '', 14, 0, 'secret', '', 0, 0),
(1030, 47.900912, 7.098207, '<p>Voici le Grand Ballon, le plus haut sommet des Vosges avec 1424m d\'altitude. Il ne faut surtout pas le confondre avec le Ballon d\'Alsace. A son sommet, on trouve une station météo reconnaissable de loin</p><button type=\"button\" name=\"button\" id=\"bouton\">Prendre la photo</button>', 'grand_ballon', 0, '', 15, 0, 'secret', '', 0, 0),
(1013, 47.980511, 7.126062, '<p>Voici le Petit Ballon, autre sommet notable avec 1272m. On y trouve notamment des vosgiennes, les vaches qui permettent de créer le munster.</p><button type=\"button\" name=\"button\" id=\"bouton\">Continuer</button>', 'vache', 0, '', 15, 0, 'secret', '', 0, 0),
(1014, 47.852573, 7.287205, '<p>L\'écomusée d\'Alsace est un musée composé d\'anciennes maisons restaurées. Vous y découvrirez des architectures typiques d\'une ancienne époque.</p><button type=\"button\" name=\"button\" id=\"bouton\">Continuer</button>', 'ecomusee', 0, '', 13, 0, 'secret', '', 0, 0),
(1015, 47.858697, 7.202948, '<p>Voici une bouteille de crémant du domaine d\'Ollwiller. Vous trouverez de multiples autres grands cru sur la route des vins le long du massif des Vosges entre Thann et Marlenheim. Les vignobles alsaciens n\'ont rien à envier à leurs compratriotes !</p><button type=\"button\" name=\"button\" id=\"bouton\">Continuer</button>', 'ollwiller', 0, '', 15, 0, 'secret', '', 0, 0),
(1016, 47.835111, 7.179516, '<p>L\'eau de Wattwiller est une autre eau bien connue en France. C\'est à ce lieu que l\'eau y est captée avant d\'âtre embouteillée. L\'Alsace est ainsi une terre de vin mais aussi une terre d\'eau de source.</p><button type=\"button\" name=\"button\" id=\"bouton\">Collecter</button>', 'wattwiller', 0, '', 15, 0, 'secret', '', 0, 0),
(1017, 47.963682, 6.837695, '<p>La tradition de Saint-Nicolas perdure dans les Vosges, cette brioche en est la preuve vivante... ou pas. Car en effet, vous allez être tentés de les dévorées en une bouchée.</p><button type=\"button\" name=\"button\" id=\"bouton\">Collecter</button>', 'saint_nicolas', 0, '', 15, 0, 'secret', '', 0, 0),
(1018, 47.854569, 6.81919, '<p>Le Saint-Nicolas ne se déguste pas qu\'en brioche. La version pain d\'épice de Saint-Nicolas est aussi un incontournable dans les Vosges.</p><button type=\"button\" name=\"button\" id=\"bouton\">Collecter</button>', 'pain_epice', 0, '', 14, 0, 'secret', '', 0, 0),
(1019, 47.810264, 7.238044, '<p>Le kouglof est probablement l\'une des pâtisseries traditionnelles les plus connues. Son caractère moelleux avec des raisins secs plaît à plus d\'un.</p><button type=\"button\" name=\"button\" id=\"bouton\">Collecter</button> ', 'kouglof', 0, '', 15, 0, 'secret', '', 0, 0),
(1020, 47.821028, 7.010596, '<p>Le club vosgien est l\'organisme qui s\'occupe du balisage dans les Vosges. Voici son emblème. Vous trouverez partout des indications pour la randonnées très pratiques (système de formes et de couleurs). On trouve rarement un meilleur système en France. Sinon, ce lieu est le Rossberg sommet secondaire des Vosges (1191 m).</p><button type=\"button\" name=\"button\" id=\"bouton\">Collecter</button>', 'club_vosgien', 0, '', 15, 0, 'secret', '', 0, 0),
(1021, 47.85472, 6.917946, '<p>Dans les Vosges, vous trouverez de nombreuses auberges à l\'image de la chaume du Rouge Gazon situé non loin de la Tête des Perches (1222 m). Vous pourrez y déguster du lard par exemple.</p><button type=\"button\" name=\"button\" id=\"bouton\">Collecter</button>', 'lard', 0, '', 15, 0, 'secret', '', 0, 0),
(1022, 47.780643, 6.908463, '<p>Dans les Vosges, on peut trouver de nombreuses sources qui sont à l\'origine du creusement des vallées. La source de la Doller est moins connue que la source de la Moselle ou de la Meurthe, mais n\'en demeure pas moins intéressante</p><button type=\"button\" name=\"button\" id=\"bouton\">Collecter</button>', 'source', 0, '', 15, 0, 'secret', '', 0, 0),
(1023, 47.884349, 6.999153, '<p>Les jardins métissés de Wesserling sont un lieu touristique intéressant. Il est possible d\'y découvrir des jardins étonnants et agençant des objets inattendus.</p><button type=\"button\" name=\"button\" id=\"bouton\">Prendre la photo</button>', 'metisse', 0, '', 15, 0, 'secret', '', 0, 0),
(1024, 47.92459, 6.658466, '<p>La crème de munster de l\'affineur Courroy est une denrée excellente dans les Vosges. D\'un point de vue, subjectif, c\'est encore meilleur que la cancoillotte.</p><button type=\"button\" name=\"button\" id=\"bouton\">Collecter</button>', 'creme_munster', 0, '', 14, 0, '', '', 0, 0),
(1025, 48.109517, 7.076771, '<p>Sur les sommets majeurs des Vosges à l\'image d\'ici au Gazon du Faing, il n\'est pas rare de trouver des chamois... surtout à l\'aube. Dans tous les cas soyez bien discrets.</p><button type=\"button\" name=\"button\" id=\"bouton\">Prendre la photo</button>', 'chamois', 0, '', 15, 0, 'secret', '', 0, 0),
(1026, 48.047933, 6.820652, '<p>Le sapin est la star des Vosges. Vous prendrez toujours du plaisr à l\'admirer au coeur de la forêt</p><button type=\"button\" name=\"button\" id=\"bouton\">Prendre la photo</button>', 'sapin', 0, '', 15, 0, 'secret', '', 0, 0),
(1027, 47.478479, 6.660058, '<p>Si vous trouvez ce secret, c\'est que vous avez envie d\'obtenir le moindre secret. Cette image n\'a rien à voir avec les Vosges, c\'est juste un plaisir personnel...</p><button type=\"button\" name=\"button\" id=\"bouton\">Prendre la photo</button>', 'borne', 0, '', 12, 0, 'secret', '', 0, 0),
(1028, 47.860584, 7.158882, '<p>Voici un autre lieu de mémoire consacré à la Première Guerre Mondiale : il s\'agit du mémorial du Vieil Armand. Vous obtenez cette fois-ci un drapeau français</p><button type=\"button\" name=\"button\" id=\"bouton\">Collecter</button>', 'france', 0, '', 15, 0, 'secret', '', 0, 0),
(1029, 47.957683, 6.839671, '<p>Les objectifs de promenades dans les Vosges comme ailleurs sont souvent des croix. La croix de Mission surmonte la ville de Cornimont et constitue un objectif intéressant.</p><button type=\"button\" name=\"button\" id=\"bouton\">Prendre la photo</button>', 'croix_mission', 0, '', 15, 0, 'secret', '', 0, 0),
(1500, 47.962571, 6.455548, '<p> Ah les thermes de Plombières-les-Bains... Leurs augustes altesses Louis-Phillipe Ier et Napoléon III les appréciaient particulièrement. Nul doute que ces eaux naturellement brûlantes raffermiront vos chairs et redonneront tonicité et explosivité à vos quadriceps endoloris ! </p>\r\n<button type=\"button\" name=\"button\" id=\"bouton\">Collecter</button>', 'aigle', 0, '', 15, 0, 'secret', '', 0, 0),
(1501, 47.889707, 6.412444, '<p> En grande capitale de la cerise, la petite bourgade est fière de vous offrir en cadeau de bienvenue des Griottines, petites cerises qui poussent sur les terres saônoises. N\'en mangez pas trop vous risqueriez de ne pas repartir ! </p>\r\n<button type=\"button\" name=\"button\" id=\"bouton\">Collecter</button>', 'griottines', 0, '', 15, 0, 'secret', '', 0, 0),
(1502, 47.889362, 6.412952, '<p> Rien de tel qu\'un petit kirsch pour se redonner du tonus ! Celui de Fougerolles est particulièrement délicat, mais si vous êtes solides, vous pouvez opter pour la version avec absinthe ajoutée ! </p>\r\n<button type=\"button\" name=\"button\" id=\"bouton\">Collecter</button>', 'kirsch', 0, '', 15, 0, 'secret', '', 0, 0),
(1503, 47.820822, 6.37725, '<p> Si Plombières ne vous a pas suffit, voilà une nouvelle occasion de faire trempette dans des bains relaxants : les thermes de Luxeuil-les-Bains se présentent à vous ! Ils existaient déjà à l\'époque romaine, mais prudence, la légende raconte que la source de chaleur n\'est autre qu\'un volcan endormi dont la ville épouse la forme du cratère... </p>\r\n<button type=\"button\" name=\"button\" id=\"bouton\">Collecter</button>', 'bains_luxeuil', 0, '', 15, 0, 'secret', '', 0, 0),
(1504, 47.8163, 6.38199, '<p> Luxeuil est une ville au patrimoine historique extrêmement riche. Vous vous trouvez actuellement sur un site de fouilles qui exhument millimètres après millimètres un crypte qui daterait peut-être du premier siècle après J-C ! </p>\r\n<button type=\"button\" name=\"button\" id=\"bouton\">Colecter</button>', 'fouilles', 0, '', 15, 0, 'secret', '', 0, 0),
(1505, 47.777762, 6.369865, '<p> Vous venez de faire un coucou à l\'un des créateurs de ce site : c\'est en effet dans ce village, La Chapelle-lès-Luxeuil, qu\'il a grandi avant de venir étudier à l\'ENSG ! </p>\r\n<button type=\"button\" name=\"button\" id=\"bouton\">Continuer</button>', 'chapelle', 0, '', 15, 0, 'secret', '', 0, 0),
(1506, 47.85502, 6.396101, '<p> Au détour des petites routes tortueuses des Vosges saônoises vous tombez nez à nez avec une petite grotte qui semble avoir été aménagée. Ce n\'est qu\'en lisant l\'écriteau à l\'entrée que vous comprenez qu\'il s\'agit de l\'ancienne antre de l\'ermite de St Valbert, qui s\'était réfugié ici pour terminer sa vie loin du tumulte du monde réelle. </p>\r\n<button type=\"button\" name=\"button\" id=\"bouton\">Collecter</button>', 'ermite', 0, '', 15, 0, 'secret', '', 0, 0),
(1507, 47.671019, 6.319823, '<p> Décidément l\'eau, ce n\'est pas une denrée rare en Haute-Saône ! Celle de Velleminfroy est très appréciée des locaux. Voilà un petit rafraîchissement pur supplémentaire pour continuer ce périple ! <\\p>\r\n<button type=\\\"button\\\" name=\\\"button\\\" id=\\\"bouton\\\">Collecter</button>', 'velleminfroy', 0, '', 15, 0, 'secret', '', 0, 0),
(1510, 47.871753, 6.508578, '<p> L\'hypoglycémie vous guette après tous ces kilomètres avalés... Heureusement vous tombez sur l\'apiculteur local de Saint-Bresson ! Rien de tel qu\'un bon miel pour se revigorer ! Vous emportez 3 pots au passage, histoire de bien alourdir votre sac déjà bondé. </p>\r\n<button type=\"button\" name=\"button\" id=\"bouton\">Collecter</button>\r\n', 'miel', 0, '', 15, 0, 'secret', '', 0, 0),
(1511, 47.808911, 6.676598, '<p> Une cascade digne de celles du Hérisson dans le Jura, le Saut de l\'Ognon, au nom quelque peu comique, est un petit coin charmant à deux pas de Servance. Ressourçant, sans mauvais jeu de mots. </p>\r\n<button type=\"button\" name=\"button\" id=\"bouton\">Collecter</button>', 'ognon', 0, '', 15, 0, 'secret', '', 0, 0),
(1512, 47.754499, 6.580744, '<p> En grand fanatique de vélo que vous êtes, vous ne pouviez résister à l\'envie de passer dans le village natal de votre idole : Thibaut Pinot, le petit gars du coin devenu un champion en gardant son côté simple et connecté à la réalité. Vous ne pouvez empêcher une petite larme de couler. </p>\r\n<button type=\"button\" name=\"button\" id=\"bouton\">Collecter</button>', 'thibaut', 0, '', 15, 0, 'secret', '', 0, 0),
(1513, 47.801543, 6.562369, '<p> Sans le savoir vous évoluez depuis un bon moment, depuis Luxeuil-les-Bains en réalité, dans la région des Mille Étangs. Le plus beau reste que cette appellation est à prendre littéralement, puisque l\'on trouve largement plus que mille étangs dans les alentours. Cela témoigne de l\'activité de gestion des campagnes des siècles récents qui donnent aujourd\'hui ces paysages typiques des Vosges Saônoises. </p>\r\n<button type=\"button\" name=\"button\" id=\"bouton\">Collecter</button>\r\n', 'étangs', 0, '', 15, 0, 'secret', '', 0, 0),
(1514, 47.706558, 6.621573, '<p> Joyau du patrimoine architectural français, la chapelle de Ronchamp, imaginée par le Corbusier, dénote dans cet environnement verdoyant qui vous entoure.\r\nAppréciez le jeu de couleurs et de contrastes dans son intérieur en clair-obscur. Pas de photos, on est d\'abord là pour apprécier avec les yeux. </p>\r\n<button type=\"button\" name=\"button\" id=\"bouton\">Collecter</button>', 'ronchamp', 0, '', 15, 0, 'secret', '', 0, 0),
(1516, 47.772671, 6.751775, '<p> La voilà. Cette fois plus d\'échappatoire. La terrible Planche des Belles Filles se dresse devant vous, ses passages à 13% déjà visibles.\r\nAllez, plus que 6.5km. Et rendez-vous en haut pour savourer cette incroyable épopée à travers les trésors des Vosges et de Haute-Saône. </p>\r\n<button type=\"button\" name=\"button\" id=\"bouton\">Collecter</button>', 'planche1', 0, '', 15, 0, 'secret', '', 0, 0),
(1518, 47.65496, 6.132762, '<p> Si vous êtes arrivés jusqu\'ici vous être réellement fortiche. Quel détour depuis votre itinéraire principal jusqu\'à ce village de Pusey, où, il faut bien le reconnaître, il n\'y plus rien d\'intéressant à voir... Plus rien, si ce n\'est qu\'un point de culture générale s\'impose : c\'est ici que naquit Jules Rimet, fondateur de la Coupe du Monde de Football qui est aujourd\'hui l\'évènement sportif le plus regardé au monde. Comme quoi... </p>\r\n<button type=\"button\" name=\"button\" id=\"bouton\">Collecter</button>', 'rimet', 0, '', 15, 0, 'secret', '', 0, 0);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
